<<<<<<< HEAD
# Site
title:              Thermoidraulica Pasini
bio:                'Thermoidraulica Pasini di Pasini Giovanni'
description:        "Thermoidraulica Pasini di Pasini Giovanni è un'azienda che opera nell'ambito di impianti :"
reading_time:       false
words_per_minute:   200
logo:               'assets/images/100.png'
background:         assets/img/placeholder-big.jpg
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             it_IT
url:                https://thermoidraulicapasini.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              thermoidraulica@libero.it
twitter:            username
facebook:           username
github-url:         username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          username1
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
=======
theme: jekyll-theme-minimal
>>>>>>> cfead18a61bc673a1aa950b3a8eb30a9554990f7
